### PR TITLE
Use the video frame's declared line stride if it is non 0

### PR DESCRIPTION
**Pull request by guillaumeriousat**
This fixes https://github.com/nocarryr/cyndilib/issues/7

There should probably be additional tests for this edge case but the testing code is a bit beyond me for the time I have to invest.

### CODE REVIEW

**Comment by nocarryr** [comment]
This is interesting.  I wouldn't be surprised that I got some of that math wrong.

One thing though:
The `_recalc_pack_info` method is also used in `VideoSendFrame`.  In that scenario, the frame pointer's line stride will always need to be set (since it's updated from user input on resolution, etc).

Maybe it would be better to add a `bint` argument to "force" the use of `NDIlib_video_frame_v2_t.line_stride_in_bytes` for instances of `VideoRecvFrame` and `VideoFrameSync`?

**Comment by nocarryr** [comment]
Something like

```cython
cdef int _recalc_pack_info(self, bint use_ptr_stride=True) except -1 nogil:
    cdef FourCC fcc = self._get_fourcc()
    cdef bint changed = False
    cdef size_t line_stride = 0
    if use_ptr_stride:
        line_stride = self.ptr.line_stride_in_bytes
    if self.pack_info.fourcc != fcc:
        self.pack_info.fourcc = fcc
        changed = True
    if self.ptr.xres != self.pack_info.xres or self.ptr.yres != self.pack_info.yres:
        self.pack_info.xres = self.ptr.xres
        self.pack_info.yres = self.ptr.yres
        changed = True
    if self.pack_info.xres == 0 or self.pack_info.yres == 0:
        return 0
    if changed:
        calc_fourcc_pack_info(&(self.pack_info))
        if use_ptr_stride:
            self.ptr.line_stride_in_bytes = self.pack_info.bytes_per_pixel * self.ptr.xres
    return 0
```

I think?  I could be wrong since I'm just typing this and can't compile right now, but hopefully you get what I mean

And then an override in `VideoSendFrame`:

```cython
cdef int _recalc_pack_info(self, bint use_ptr_stride=True) except -1 nogil:
    return VideoFrame._recalc_pack_info(self, False)
```

**Comment by guillaumeriousat** [comment]
Woops, I didn't think I was breaking the VideoSendFrame by doing that...

I made a commit with the changes you suggested and it still works for my use case !

Thanks for the library and the responsivity !

**Comment by nocarryr** [comment]
LGTM
Thanks for finding the issue and the fix!

**Pull request merged**
